### PR TITLE
pocolog 2.0

### PR DESCRIPTION
**Pull request by doudou**
**NOTE** this is barely tested in production (there are unit tests, but it hasn't been used). I put it there if there are some brave souls that would be interested. I'm not even sure that the common tools such as `rock-replay` still work.

Over time, `Logfiles` had become a pot-pourri of a lot of stuff, with an incredible amount of state tracking. This refactors the code to separate concerns a bit, avoiding that pitfall.

It should be "user API compatible" (i.e. the few often-used methods should not have changed), but other than this it's definitely backward-incompatible.

### CODE REVIEW

**Comment by 2maz** [comment]
Currently breaks rock-replay:

```
/opt/workspace/dev/tools/orocos.rb/lib/orocos/log/replay.rb:181:in `rescue in open': uninitialized constant Pocolog::Logfiles::MissingPrologue (NameError)
Did you mean?  Pocolog::MissingPrologue
	from /opt/workspace/dev/tools/orocos.rb/lib/orocos/log/replay.rb:175:in `open'
```
After changing to Pocolog::MissingPrologue ..
Encountering the next error due to DataStream missing attribute typename (so adapted add_port to just check and use stream.type.name)
```
tools/orocos.rb/lib/orocos/log/task_context.rb:301:in `initialize': Cannot create OutputPort out of Pocolog::DataStream (RuntimeError)
	from /opt/workspace/dev/tools/orocos.rb/lib/orocos/log/task_context.rb:778:in `new'
	from /opt/workspace/dev/tools/orocos.rb/lib/orocos/log/task_context.rb:778:in `add_port'

```

I stopped then here:
```
Aligning streams. This can take a long time
pocolog.rb[INFO]: adding 2 streams with 4001 samples
pocolog.rb[INFO]: concatenated indexes in 0.00 seconds
pocolog.rb[INFO]: built full index in 0.00 seconds
/opt/workspace/dev/tools/pocolog/lib/pocolog/stream_aligner.rb:572:in `[]': no implicit conversion from nil to integer (TypeError)
	from /opt/workspace/dev/tools/pocolog/lib/pocolog/stream_aligner.rb:572:in `first_sample_pos'
```

**Comment by doudou** [comment]
Hi @2maz. Thanks for looking into it. As put in the disclaimer, it's 100% untested apart from the test suite. Moreover, I want to build a good benchmarking suite to use as baseline for the future.

There's something weird: `Pocolog::Logfiles::MissingPrologue` does exist: https://github.com/rock-core/tools-pocolog/blob/refactoring/lib/pocolog/file.rb#L64.

The second point, I would prefer re-adding typename to DataStream. Backward compatibility is important in this case IMO.

And aligning two streams do work on my test setup.

Would you be interested in helping with that stuff ? Or just general testing ?

**Comment by 2maz** [comment]
> Hi @2maz. Thanks for looking into it. As put in the disclaimer, it's 100% untested apart from the test suite. Moreover, I want to build a good benchmarking suite to use as baseline for the future.

No problem, I read the disclaimer.

> There's something weird: Pocolog::Logfiles::MissingPrologue does exist: https://github.com/rock-core/tools-pocolog/blob/refactoring/lib/pocolog/file.rb#L64.

That's indeed interesting, but checked and trying to reload this file before the exception leads to the following error and it that does not look like pocolog/file has been loaded before?
`
TypeError: superclass mismatch for class NotEnoughData
from /opt/workspace/rock_master/tools/pocolog/lib/pocolog/file.rb:9:in `<module:Pocolog>'
`

> The second point, I would prefer re-adding typename to DataStream. Backward compatibility is important in this case IMO.

+1

> Would you be interested in helping with that stuff ? Or just general testing ?

For now, I am afraid I will only be able to do some testing

**Comment by doudou** [comment]
> For now, I am afraid I will only be able to do some testing

No problem, thanks for it anyways. I won't have much time in the next weeks to work on this either ...

**Comment by saarnold** [comment]
I gave it a try. It seems to have some problems when replying a folder containing a bunch of logfiles:
```
pocolog.rb[INFO]: done
Aligning streams. This can take a long time
pocolog.rb[INFO]: adding 455 streams with 1430055 samples
pocolog.rb[INFO]: concatenated indexes in 0.27 seconds
pocolog.rb[INFO]: built full index in 0.64 seconds
/home/sirius/silana/tools/pocolog/lib/pocolog/stream_aligner.rb:572:in `[]': no implicit conversion from nil to integer (TypeError)
	from /home/sirius/silana/tools/pocolog/lib/pocolog/stream_aligner.rb:572:in `first_sample_pos'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:466:in `first_sample_pos'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/task_context.rb:302:in `first_sample_pos'
	from /home/sirius/silana/tools/utilrb/lib/utilrb/thread_pool.rb:440:in `sync'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit_items.rb:1071:in `initialize'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit_items.rb:1094:in `new'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit_items.rb:1094:in `append_port'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit_items.rb:495:in `block (2 levels) in initialize'
	from (eval):6:in `block in once_on_reachable'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/async/object_base.rb:51:in `call'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/async/object_base.rb:296:in `really_add_listener'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/async/log/ports.rb:127:in `really_add_listener'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/async/object_base.rb:287:in `block in add_listener'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit.rb:142:in `block in exec'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `exec'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit.rb:146:in `exec'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:105:in `replay'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:150:in `<main>'
	from /home/sirius/silana/tools/utilrb/lib/utilrb/event_loop.rb:622:in `step'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit.rb:142:in `block in exec'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /home/sirius/.autoproj/gems/ruby/2.3.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `exec'
	from /home/sirius/silana/gui/vizkit/lib/vizkit/vizkit.rb:146:in `exec'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:105:in `replay'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:150:in `<main>'
```
or 
```
orocos.rb[ERROR]: Cannot load logfiles
/home/sirius/silana/tools/pocolog/lib/pocolog/stream_info.rb:85:in `concat': the IO range of the given stream starts before the range of self (ArgumentError)
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:269:in `block (2 levels) in load_stream_info'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:266:in `each'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:266:in `each_with_index'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:266:in `block in load_stream_info'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:260:in `each'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:260:in `each_with_index'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:260:in `load_stream_info'
	from /home/sirius/silana/tools/pocolog/lib/pocolog/logfiles.rb:113:in `initialize'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:1028:in `new'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:1028:in `block (2 levels) in load'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:1018:in `each_value'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:1018:in `block in load'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:996:in `each'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:996:in `load'
	from /home/sirius/silana/tools/orocos.rb/lib/orocos/log/replay.rb:176:in `open'
	from /home/sirius/silana/gui/vizkit/bin/rock-replay:89:in `<main>'
```
I couldn't identify if one particular logfile is responsible for the error. Replaying single files seems to work however.
When using the slider to jump to a particular position I got the following error:
```
failed to unmarshal sample in block at position 15970407: std::bad_alloc
```
This seems to occur on any stream.

**Comment by doudou** [comment]
@saarnold, thanks !

There were two bugs lurkling in here. For the record, I did use the branch extensively a few weeks back without problems.... It's just that I use the WIP syskit-pocolog tooling, which normalizes log datasets to have one file == one stream. These bugs were not happening in this particular case.

The first one should be fixed by https://github.com/rock-core/tools-orocosrb/pull/127
I've pushed a fix to the branch for the second one.

**Comment by saarnold** [comment]
I gave it another try using the orocos.rb branch rock-core/tools-orocosrb#127.
The exceptions seem to be fixed :+1: 
What I noticed is a difference in the actual replayed sample (and sample time) to the shown time, current speed and port in the control GUI. They seem to drift apart and also don't recover when jumping to a certain index.

**Comment by doudou** [comment]
> What I noticed is a difference in the actual replayed sample (and sample time) to the shown time, current speed and port in the control GUI. They seem to drift apart and also don't recover when jumping to a certain index.

Thanks for testing ! I'll have a look. Could you give more details ? Just to be sure I completely understand.

**Comment by saarnold** [comment]
It seems that the replay speed is currently not affected by the target speed. The GUI shows a constant speed of ~0.1 and the actual replay speed according to `rock-hz` is 2 times the frequency the samples have been recorded in.

**Comment by doudou** [comment]
Could you maybe share the logfile you're having ? I don't manage to reproduce the behavior ...

**Comment by saarnold** [comment]
> Could you maybe share the logfile(s) that cause this ?

Sure I put a small logfile created in 2017 here: https://cloud.dfki.de/owncloud/index.php/s/p7xJm7taY8N9fWN

> I don't manage to reproduce the behavior ...

Since I seem to have the same issue with any log, maybe there is a dependency that isn't up to date or not on the correct branch. Are there other necessary overrides?
I'll try it with a fresh bootstrap in the next days.

**Comment by doudou** [comment]
> Since I seem to have the same issue with any log, maybe there is a dependency that isn't up to date or not on the correct branch. Are there other necessary overrides?
> I'll try it with a fresh bootstrap in the next days.

My fault. I was testing in a too stupid setup to be anywhere close to useful. Sorry. I'm reproducing now ...

**Comment by doudou** [comment]
So, the problem was the last commit ... which I didn't mean to push in the first place. I've forced-push the branch to remove it (you'll have to reset --hard to get rid of it too). The "good" head is 4e91297244ac5543ed53a1b741fc8a73d782b20d.

**Comment by doudou** [comment]
@saarnold, @2maz and @g-arjones I've been using this branch for years now. @saarnold had trouble with it in 2018 (I am very sorry I didn't resolve them then ...)

If you are still using the ruby-side pocolog, I would appreciate it if you could test the last state of the branch.

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
Ping @2maz @saarnold

**Comment by 2maz** [comment]
Just threw it one some available logs. Mainly went fine.
For using multiple log files, I found the following.
It is not obvious from the CLI help what restrictions exist/should happen, when multiple files are used.

```
pocolog port_requests.0.log transformer_broadcaster.0.log                                                                                                                 [17:04:36]
pocolog.rb[INFO]: loading file info from ./port_requests.0.idx... 
pocolog.rb[INFO]: loading file info from ./transformer_broadcaster.0.idx... 
Traceback (most recent call last):
	13: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/bin/pocolog:705:in `<main>'
	12: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/bin/pocolog:572:in `execute'
	11: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/bin/pocolog:572:in `new'
	10: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/bin/pocolog:107:in `initialize'
	 9: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/bin/pocolog:107:in `new'
	 8: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:113:in `initialize'
	 7: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:260:in `load_stream_info'
	 6: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:260:in `each_with_index'
	 5: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:260:in `each'
	 4: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:266:in `block in load_stream_info'
	 3: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:266:in `each_with_index'
	 2: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:266:in `each'
	 1: from /home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/logfiles.rb:269:in `block (2 levels) in load_stream_info'
/home/dfki.uni-bremen.de/roehr/workspace/rock_master/tools/pocolog/lib/pocolog/stream_info.rb:87:in `concat': the logical time range of the given stream starts (2958639379048160) before the range of self (2958642002377524) (ArgumentError)
```

**Comment by doudou** [comment]
> Just threw it one some available logs. Mainly went fine.
> For using multiple log files, I found the following.
> It is not obvious from the CLI help what restrictions exist/should happen, when multiple files are used.

Should not break existing behavior. To be honest, it's not clear to me what restrictions existed in the current implementation. Could you do this fine ?

**Comment by doudou** [comment]
Not

~~~
[DEPRECATED] utilrb/hash/slice is deprecated, use backports' backports/2.5.0/hash/slice instead or the built-in method in Ruby >= 2.5
File data is in little endian byte order
pocolog.rb[INFO]: building index ./smart_shunt.0.idx ...
Traceback (most recent call last):
        9: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:703:in `<main>'
        8: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:574:in `execute'
        7: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:378:in `execute'
        6: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:405:in `display_file_info'
        5: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:575:in `streams'
        4: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:437:in `each_data_block'
        3: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:335:in `each_block'
        2: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:438:in `block in each_data_block'
        1: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:380:in `handle_block'
/home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:698:in `read_stream_declaration': stream velocity_control.cmd_out changed definition (RuntimeError)
        9: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:703:in `<main>'
        8: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:574:in `execute'
        7: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:378:in `execute'
        6: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/bin/pocolog:405:in `display_file_info'
        5: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:575:in `streams'
        4: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:437:in `each_data_block'
        3: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:335:in `each_block'
        2: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:438:in `block in each_data_block'
        1: from /home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:380:in `handle_block'
/home/doudou/dev/tidewise/wetpaint/tools/pocolog/lib/pocolog/file.rb:698:in `read_stream_declaration': stream velocity_control.cmd_out changed definition at position 2881 (RuntimeError)
~~~

Multiple files given on the command line are interpreted as sequential, that is the same log but following each other.

**Comment by doudou** [comment]
(and thanks for spending the time to look into it, @2maz !)

**Comment by saarnold** [comment]
I also tested it on some logfiles older and newer once, seems all to work fine. Very nice :+1:

**Comment by doudou** [comment]
Thanks guys ... And my apologies for this never-ending pull request.

**Pull request merged**
