### PR TITLE
Fix manifest.xml

### PR DESCRIPTION
**Pull request by 2maz**
Align dependencies required in the Rakefile with the manifest.xml

### CODE REVIEW

**Comment by doudou** [comment]
Actually, rbtree is not used anymore

**Comment by 2maz** [comment]
The dependency is listed in the Rakefile and benchmarks require it:
> benchmarks/sorted_set.rb:require 'rbtree'

It can be optional, but the overall dependency definition should be consistent.

**Comment by doudou** [comment]
> benchmarks require it:

Yes. But benchmarks is a benchmark "for documentation purposes". It's not part of the lib. Let's not add mandatory dependencies on all possible sorting methods just because I did the right thing and actually benchmarked them.

> The dependency is listed in the Rakefile

That was my point ... it should be removed from the Rakefile instead of added to manifest.xml.

> the overall dependency definition should be consistent

In principle, one is rock-specific (so can be tuned to Rock's needs) while the other is Rubygem-specific (so can be tuned to the need of a standalone Gem). Any reason the two need to be in sync ?

**Comment by 2maz** [comment]
So far I had more a unified view on Rakefile and manifest.xml, so I rechecked: when generating a debian package for ruby packages we use the Rakefile information and the manifest.xml.
So the inconsistency arises from this unified view and the fact that we use autoproj to figure out the required dependencies for a package, but use the combined information of dependencies for the debian package.
That leads to a package which by definition in debian/control requires rbtree as prerequisite, but rbtree is not available because autoproj didn't have this information.

I can adapt this behaviour and discard Rakefile information, but without further mechanisms, we will end up installing ruby files (in this case the benchmark files) which will not be usable out-of-the-box after installing the package.
IMO we should not make it harder for a user to run scripts or (test-)utilities that are part of a package (prebuilt or not) -- though while trying right now, 'priority_queue' is missing as dependency as well ...

**Comment by doudou** [comment]
> IMO we should not make it harder for a user to run scripts or (test-)utilities that are part of a package (prebuilt or not)

This is IMO the wrong view. I can add a lot of scripts that have *nothing* to do with the package's function, for documentation/development reasons. There's no reason for the end-user to run them, so they're mine. The benchmarks are exactly this case. I've benchmarked the different sorting methods to pick the right one. Keeping the script is IMO important for later reference, but pocolog cannot depend on *all* the methods that have been tested.

What the package gives the end user is a library to use. The rest is the developer's. That includes the tests. End users should not depend on the test packages (which is basically why there's a test_depend in autoproj)

**Comment by 2maz** [comment]
I agree in the case when we take care of not shipping the files, but if I ship them -- they should run.
Regarding rbtree, I verified the shipping part and gem2deb does indeed only pick ruby standard directories  and ignores the benchmark directory. So, sorry for 'much ado about nothing' - I will leave it out from the manifest.xml. 
For the packaging we try to adapt to solely rely on manifest.xml data for packaging and see if that is sufficient.

Regarding the test_depend: where is "test_depend" introduced -- is that introduced in autoproj v2?
Otherwise, I would set such dependencies as optional.

**Comment by doudou** [comment]
> if I ship them -- they should run.

Suit yourself. If that's your policy, then remove the benchmark files from the packaging. It's nonsensical to me (and contrary from the common practice), but if you insist in wasting your time ...

> For the packaging we try to adapt to solely rely on manifest.xml data for packaging and see if that is sufficient.

What for ? If we agree on synchronizing the Rakefile and manifest.xml, why spend resources doing that ?

> Otherwise, I would set such dependencies as optional.

`test_depend` been there for a long time, and it is not `depend_optional`. It's "install only if the user wants to run the tests". Because installing and building tests takes time and is rarely used. Even more so in prebuilt packages (have you ever ran tests from a prebuilt package ?)

**Comment by 2maz** [comment]
> Suit yourself. If that's your policy, then remove the benchmark files from the packaging. It's nonsensical to
 me (and contrary from the common practice), but if you insist in wasting your time ...

zero effort -- as I said, gem2deb does only package default directories

> What for ? If we agree on synchronizing the Rakefile and manifest.xml, why spend resources doing that ?

If they are in sync then using the manifest.xml is (a) sufficient and (b) given that from my experience the Rakefile seems to be less maintained, seems to me less of my time going after maintainers ...

> test_depend been there for a long time, and it is not depend_optional

I did not say it should be the same just did not truly know about the behaviour specification of these tags -- there is no clear documentation on these manifest tags, and I was asking after doing a quick grep on autoproj/autobuild for 'test_depend' which ran into void (so I had to follow through the code)

> Even more so in prebuilt packages (have you ever ran tests from a prebuilt package ?)

Tests/Examples, maybe rarely, but yes, actually just few days ago. Eventually, falls back to the same thing for me: if you ship tests (which they typically are not), they should run.

**Comment by doudou** [comment]
> there is no clear documentation on these manifest tags

You mean ... Rock's documentation is left to rot and shitty ?

<shock on my face>

Sorry for the sarcasm, but I really had to ....

> (so I had to follow through the code)

You should try *asking* every once in a while. That's really one of your main issues, you go all the way into the code before even trying to *ask a simple question*. I'm still wondering why you didn't ran away from Roby/Syskit years ago screaming - given that I so rarely had a question from you.

**Comment by doudou** [comment]
> Eventually, falls back to the same thing for me: if you ship tests (which they typically are not), they should run.

Again, this goes against the common practice.

If only for RubyGems (what's here), you do have a separation between "development" and "usage" dependencies, because no user actually wants the myriad of development packages required to run the tests (which a user usually never runs)

**Pull request merged**
