### PR TITLE
add missing dependency: rbtree

### PR DESCRIPTION
**Pull request by D-Alex**

### CODE REVIEW

**Comment by doudou** [comment]
rbtree is not used anymore, the "right fix" would be to remove it from stream_aligner.rb

Could you test that ?

**Comment by D-Alex** [comment]
Exporting time intervals via rock-replay is at the moment completly broken. There are so many bugs in Pocolog that I stopped working on master after digging into the code for 1h. I pushed my changes I did so far to this branch. But still with this changes no samples are exported. Maybe you have an idea what goes wrong.

If you want to trigger the bug just try to export an time interval of a logfile with rock-replay

**Comment by doudou** [comment]
Hey. Try to revert #3 and/or #4 and say if it fixes your problems.

**Comment by doudou** [comment]
The main issue with pocolog is that the stream aligner test suite has not been maintained when Janosch reimplemented it, is really not enough, and there's a lot of very sensitive stuff in there ... Hardly a great combination.

**Comment by doudou** [comment]
> The main issue with pocolog is that the stream aligner test suite has not been maintained when Janosch reimplemented it, is really not enough, and there's a lot of very sensitive stuff in there

To clarify this, given the current situation, I do not intend to blame Janosch for this. pocolog's test suite has not been well-maintained by all people who touched it.

**Comment by doudou** [comment]
Could you try this out: https://github.com/rock-core/tools-pocolog/pull/6 ?

**Comment by doudou** [comment]
The rbtree require has been removed by #6

**Pull request closed without merging**
